shared:
  output_path: ${USER}/policy_model/nes_150M_168
  n_seq_timesteps: 128
  tokenizer:
    type: "conv"
    conv_tokenizer_config:
      num_tokens: 1

# Policy Model Configuration
# dim=1024  layers=10  heads=16  => ~150M parameters
policy_model:
  n_transformer_layers: 10
  n_q_head: 16
  n_kv_head: 16
  transformer_dim: &transformer_dim 1024
  mask_block_size: 128
  attention_history_len: [128, 128, 128, 128, 128, 128, 128, 128, 128, 128]
  n_kv_sink_tokens: 0
  model_type: "dense"
  dropout: 0.2
  use_vision: true
  in_channels: 1
  frame_size: 168
  focal_gamma: 0.0
  class_weights: [0.029, 0.232, 0.102, 2.442, 0.126, 0.772, 0.521, 2.442, 0.016, 0.107, 0.042, 2.442, 0.075, 0.863, 0.105, 2.442, 0.048, 0.546, 0.082, 2.442, 0.425, 0.653, 0.705, 2.442, 0.019, 0.193, 0.040, 2.442, 1.727, 1.410, 2.442, 2.442, 0.368, 1.727, 0.653, 2.442]
  ablate: [] # ['action','img']


stage3_finetune:
  optim:
    learning_rate: 0.0001
    weight_decay: 0.0001
    beta_1: 0.9
    beta_2: 0.999

  n_epochs: 5
  n_val_recordings: 300
  accumulate_grad_batches: 32
  checkpoint_dir: tmp/checkpoints/nes_policy

  training_dataset:
    batch_size: &stage3_batch_size 4
    data_folder: annotate/bc_data/level1_grey_168
    num_workers: 8

  validation_datasets:
    - batch_size: *stage3_batch_size
      validation_name: "overall"
      num_workers: 2


wandb:
  enabled: false
  project: "policy_model"
  exp_name: "contra-nes-168"
