shared:
  output_path: ${USER}/policy_model/nes_10M
  n_seq_timesteps: 128
  frame_height: 192
  frame_width: 192
  tokenizer:
    type: "conv"
    conv_tokenizer_config:
      num_tokens: 1

# Policy Model Configuration
# dim=288  layers=7  heads=8  dec_layers=2  => 9.87M parameters
policy_model:
  n_transformer_layers: 7
  n_q_head: 8
  n_kv_head: 8
  n_thinking_tokens: 1
  transformer_dim: &transformer_dim 288
  mask_block_size: 128
  attention_history_len: [128, 128, 128, 128, 128, 128, 128]
  n_kv_sink_tokens: 0
  model_type: "dense"
  dropout: 0.15
  action_decoder:
    embed_dim: *transformer_dim
    n_layers: 2
    n_heads: 4


stage3_finetune:
  optim:
    learning_rate: 0.0003
    weight_decay: 0.01
    beta_1: 0.9
    beta_2: 0.999

  n_epochs: 30
  n_val_recordings: 50
  accumulate_grad_batches: 16

  training_dataset:
    batch_size: &stage3_batch_size 32
    local_prefix: dataset
    data_folder: annotate/bc_data/level_all_ram
    always_labelled: true
    warn_on_starvation: false
    rand_augmentation:
      fraction_augmented: 1.0
      augmentations:
        - spatial_transform
        - color
        - planckian
        - iso_noise
        - translation
        - random_blur
        - sharpness
    n_preprocess_threads_per_gpu: 1
    preprocessed_chunks_queue_size_per_gpu: 1
    shuffle_buffer_size_per_gpu: 1900
    dataset_worker_num_workers_per_gpu: 1
    dataset_worker_prefetch_factor: 1
    shuffled_chunks_queue_size_per_gpu: 1

  validation_datasets:
    - batch_size: *stage3_batch_size
      local_prefix: dataset
      validation_name: "overall"
      always_labelled: true
      n_preprocess_threads_per_gpu: 1
      preprocessed_chunks_queue_size_per_gpu: 1
      shuffled_chunks_queue_size_per_gpu: 1
      dataset_worker_prefetch_factor: 1
      warn_on_starvation: false


wandb:
  enabled: false
  project: "policy_model"
  exp_name: "contra-nes-10m"
